npmRegistries:
  //gitlab.com/api/v4/projects/30427310/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: %GITLAB_TOKEN%

npmScopes:
  cloudgraph:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/30427310/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/30427310/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
