---
branches:
  - name: alpha
    channel: alpha
    prerelease: true
  - name: beta
    channel: beta
    prerelease: true
  - name: main

dryRun: false

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
  - - "@semrel-extra/npm"
    - npmPublish: true
  - "@semantic-release/github"
verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "@semrel-extra/npm"
prepare:
  - "@semantic-release/changelog"
  - "@semrel-extra/npm"
  - - "@semantic-release/git"
    - message: "chore(release): @cloudgraph/policy-pack-aws-cis-1.3.0 ${nextRelease.version} \n\n${nextRelease.notes}"
publish:
  - "@semantic-release/github"
  - "@semrel-extra/npm"
success: false
fail: false
tagFormat: "@cloudgraph/policy-pack-aws-cis-1.3.0@${version}"
