---
branches:
  - name: main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - package.json
  - - "@semantic-release/npm"
    - npmPublish: false
  - "@semantic-release/gitlab"
verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/gitlab"
prepare:
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - - "@semantic-release/git"
    - message: "chore(publish): ${nextRelease.version} \n\n${nextRelease.notes}"
publish:
  - "@semantic-release/gitlab"
release:
   noCi: true
success: false
fail: false
repository:
  type: git
  url: git@gitlab.com:auto-cloud/cloudgraph/policy-packs.git
  directory: src/aws/cis-1.2.0
tagFormat: "${version}"
