---
branches:
  - name: alpha
    channel: alpha
    prerelease: true
  - name: beta
    channel: beta
    prerelease: true
  - name: main

dryRun: false

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
  - - "semantic-release-pnpm"
    - npmPublish: true
  - "@semantic-release/github"
verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - "semantic-release-pnpm"
prepare:
  - "@semantic-release/changelog"
  - "semantic-release-pnpm"
  - - "@semantic-release/git"
    - message: "chore(release): @cloudgraph/policy-pack-gcp-nist-800-53-rev4 ${nextRelease.version} \n\n${nextRelease.notes}"
publish:
  - "@semantic-release/github"
  - "semantic-release-pnpm"
success: false
fail: false
tagFormat: "@cloudgraph/policy-pack-gcp-nist-800-53-rev4@${version}"
