---
name: publish

on:
  push:
    branches:
      - alpha
      - beta
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.gh_token}}

      - uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen
          cache: 'npm'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.gh_token}}

      - name: Lint
        run: npm run lint
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.gh_token}}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run release
        env:
          NODE_ENV: "cicd"
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.gh_token}}
          GIT_AUTHOR_NAME: "autocloud-deploy-bot"
          GIT_AUTHOR_EMAIL: "no-reply@autocloud.dev"
          GIT_COMMITTER_NAME: "autocloud-deploy-bot"
          GIT_COMMITTER_EMAIL: "no-reply@autocloud.dev"